import { Language } from '../interfaces';

export const languageOptions: Language[] = [
  { shortCode: 'en', languageName: 'English', fullLocaleCode: 'en-US' },
  { shortCode: 'es', languageName: 'Spanish', fullLocaleCode: 'es-ES' },
  { shortCode: 'fr', languageName: 'French', fullLocaleCode: 'fr-FR' },
  { shortCode: 'de', languageName: 'German', fullLocaleCode: 'de-DE' },
  { shortCode: 'zh', languageName: 'Chinese (Simplified)', fullLocaleCode: 'zh-CN' },
  { shortCode: 'ja', languageName: 'Japanese', fullLocaleCode: 'ja-JP' },
  { shortCode: 'ko', languageName: 'Korean', fullLocaleCode: 'ko-KR' },
  { shortCode: 'pt', languageName: 'Portuguese', fullLocaleCode: 'pt-PT' },
  { shortCode: 'ru', languageName: 'Russian', fullLocaleCode: 'ru-RU' },
  { shortCode: 'ar', languageName: 'Arabic', fullLocaleCode: 'ar-SA' },
  { shortCode: 'it', languageName: 'Italian', fullLocaleCode: 'it-IT' },
  { shortCode: 'nl', languageName: 'Dutch', fullLocaleCode: 'nl-NL' },
  { shortCode: 'sv', languageName: 'Swedish', fullLocaleCode: 'sv-SE' },
  { shortCode: 'no', languageName: 'Norwegian', fullLocaleCode: 'no-NO' },
  { shortCode: 'da', languageName: 'Danish', fullLocaleCode: 'da-DK' },
  { shortCode: 'fi', languageName: 'Finnish', fullLocaleCode: 'fi-FI' },
  { shortCode: 'pl', languageName: 'Polish', fullLocaleCode: 'pl-PL' },
  { shortCode: 'tr', languageName: 'Turkish', fullLocaleCode: 'tr-TR' },
  { shortCode: 'cs', languageName: 'Czech', fullLocaleCode: 'cs-CZ' },
  { shortCode: 'hu', languageName: 'Hungarian', fullLocaleCode: 'hu-HU' },
  { shortCode: 'ro', languageName: 'Romanian', fullLocaleCode: 'ro-RO' },
  { shortCode: 'he', languageName: 'Hebrew', fullLocaleCode: 'he-IL' },
  { shortCode: 'th', languageName: 'Thai', fullLocaleCode: 'th-TH' },
  { shortCode: 'vi', languageName: 'Vietnamese', fullLocaleCode: 'vi-VN' },
  { shortCode: 'ms', languageName: 'Malay', fullLocaleCode: 'ms-MY' },
  { shortCode: 'id', languageName: 'Indonesian', fullLocaleCode: 'id-ID' },
  { shortCode: 'uk', languageName: 'Ukrainian', fullLocaleCode: 'uk-UA' },
];
